// PDF Export Functionality using jspdf

import jsPDF from 'jspdf';

export function exportScheduleCToPDF(scheduleCResult: any, transactions: any[]) {
  const doc = new jsPDF();

  // TaxFlow US branding header
  doc.setFontSize(16);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(0, 229, 255); // Electric blue color (#00E5FF)
  doc.text('TaxFlow US', 20, 15);
  doc.setTextColor(0, 0, 0); // Reset to black
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.text('Automated Tax Reporting Platform', 20, 22);

  // IRS-style header
  doc.setFontSize(9);
  doc.setFont(undefined, 'bold');
  doc.text('Department of the Treasury', 150, 15, { align: 'right' });
  doc.text('Internal Revenue Service', 150, 22, { align: 'right' });
  doc.setFont(undefined, 'normal');
  doc.text('Form 1040 Schedule C (2024)', 150, 29, { align: 'right' });

  // Form title
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('Profit or Loss From Business', 105, 40, { align: 'center' });
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.text('(Sole Proprietorship)', 105, 47, { align: 'center' });

  // Line items with IRS-style formatting
  let y = 60;
  const lineItems = [
    { line: '1', description: 'Gross receipts or sales', amount: scheduleCResult.line1_grossReceipts },
    { line: '2', description: 'Returns and allowances', amount: scheduleCResult.line2_returns },
    { line: '3', description: 'Net receipts (Line 1 - Line 2)', amount: scheduleCResult.line3_netReceipts },
    { line: '4', description: 'Cost of goods sold', amount: scheduleCResult.line4_costOfGoodsSold },
    { line: '7', description: 'Gross profit (Line 3 - Line 4)', amount: scheduleCResult.line7_grossProfit },
    { line: '28', description: 'Total expenses', amount: scheduleCResult.line28_totalExpenses },
    { line: '29', description: 'Net profit (or loss) (Line 7 - Line 28)', amount: scheduleCResult.line29_netProfit },
  ];

  lineItems.forEach(item => {
    doc.setFontSize(9);
    doc.setFont(undefined, 'bold');
    doc.text(`${item.line}`, 20, y);
    doc.setFont(undefined, 'normal');
    doc.text(item.description, 35, y);
    doc.text(`$${item.amount.toFixed(2)}`, 180, y, { align: 'right' });
    y += 12;
  });

  // Detailed expenses
  y += 5;
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  doc.text('Detailed Expense Breakdown:', 20, y);
  y += 10;

  scheduleCResult.lineItems.forEach((item: any) => {
    doc.setFontSize(8);
    doc.setFont(undefined, 'bold');
    doc.text(`${item.line}`, 20, y);
    doc.setFont(undefined, 'normal');
    doc.text(item.description, 35, y);
    doc.text(`$${item.amount.toFixed(2)}`, 180, y, { align: 'right' });
    y += 8;
  });

  // IRS-style footer
  doc.setFontSize(8);
  doc.setFont(undefined, 'normal');
  doc.text('For Privacy Act and Paperwork Reduction Act Notice, see instructions.', 20, 270);
  const currentDate = new Date();
  const formattedDate = currentDate.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  doc.text(`Generated by TaxFlow US on ${formattedDate}`, 20, 275);

  // Add audit trail page
  doc.addPage();

  // Audit trail header
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.setTextColor(0, 229, 255);
  doc.text('Audit Trail', 20, 15);
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');
  doc.text('Transaction Details Contributing to Schedule C Totals', 20, 22);

  // Table header
  y = 35;
  doc.setFontSize(8);
  doc.setFont(undefined, 'bold');
  doc.setFillColor(240, 240, 240);
  doc.rect(20, y - 5, 170, 8, 'F');
  doc.text('Date', 22, y);
  doc.text('Description', 50, y);
  doc.text('Category', 110, y);
  doc.text('Platform', 140, y);
  doc.text('Amount', 180, y, { align: 'right' });
  y += 8;
  doc.setFont(undefined, 'normal');

  // Transaction details
  transactions.forEach((tx: any) => {
    const txDate = tx.transaction_date?.toDate ? tx.transaction_date.toDate() : new Date(tx.transaction_date);
    const formattedTxDate = txDate.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });

    doc.text(formattedTxDate, 22, y);
    doc.text(tx.description || 'N/A', 50, y);
    doc.text(tx.categoryId || 'Uncategorized', 110, y);
    doc.text(tx.platform || 'N/A', 140, y);

    const amount = tx.amount;
    doc.setTextColor(amount >= 0 ? 0 : 200, amount >= 0 ? 100 : 0, 0);
    doc.text(`$${amount.toFixed(2)}`, 180, y, { align: 'right' });
    doc.setTextColor(0, 0, 0);

    y += 7;

    // Add new page if needed
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  // Audit trail footer
  doc.setFontSize(8);
  doc.setFont(undefined, 'normal');
  doc.text(`Total Transactions: ${transactions.length}`, 20, 280);
  doc.text('This audit trail provides a complete record of all transactions included in this Schedule C.', 20, 285);

  doc.save(`IRS_ScheduleC_2024_${new Date().toISOString().split('T')[0]}.pdf`);
}

export function exportSalesTaxToPDF(salesData: any[]) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  doc.text('TaxFlow US - Sales Tax Summary Report', 20, 15);
  doc.setFontSize(12);
  doc.text('Multi-State Sales Tax Nexus Analysis', 20, 25);

  // Summary section
  let y = 40;
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  doc.text('Report Summary:', 20, y);
  y += 10;
  doc.setFont(undefined, 'normal');
  doc.text(`Total Jurisdictions: ${salesData.length}`, 20, y);
  y += 8;
  const nexusReached = salesData.filter((s: any) => s.nexusReached).length;
  doc.text(`Nexus Reached: ${nexusReached}`, 20, y);
  y += 8;
  const atRisk = salesData.filter((s: any) => !s.nexusReached && s.percentage >= 80).length;
  doc.text(`At Risk (80%+): ${atRisk}`, 20, y);

  // Table header
  y += 15;
  doc.setFontSize(9);
  doc.setFont(undefined, 'bold');
  doc.text('Province', 20, y);
  doc.text('Total Sales', 70, y);
  doc.text('Tax Collected', 110, y);
  doc.text('Nexus Threshold', 150, y);
  doc.text('Status', 180, y);
  y += 8;
  doc.setFont(undefined, 'normal');

  // Province data
  salesData.forEach((state: any) => {
    doc.text(state.provinceCode, 20, y);
    doc.text(`$${state.totalSales.toFixed(2)}`, 70, y);
    doc.text(`$${state.taxCollected.toFixed(2)}`, 110, y);
    doc.text(`$${state.nexusThreshold.toLocaleString()}`, 150, y);
    doc.setFont(undefined, 'bold');
    doc.text(state.nexusReached ? 'NEXUS REACHED' : 'Below Limit', 180, y);
    doc.setFont(undefined, 'normal');
    y += 8;
  });

  // Footer
  doc.setFontSize(8);
  doc.setFont(undefined, 'normal');
  doc.text(`Generated by TaxFlow US on ${new Date().toLocaleDateString()}`, 20, 280);

  doc.save(`SalesTax_Nexus_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}

export function exportReconciliationToPDF(report: any) {
  const doc = new jsPDF();

  // Header
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  doc.text('TaxFlow US - 1099-NEC Reconciliation Report', 20, 15);
  doc.setFontSize(12);
  doc.text('Platform Payouts vs Bank Deposits', 20, 25);

  // Summary section
  let y = 40;
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  doc.text('Reconciliation Summary:', 20, y);
  y += 10;
  doc.setFont(undefined, 'normal');
  doc.text(`Total Items: ${report.totalItems}`, 20, y);
  y += 8;
  doc.text(`Reconciled: ${report.reconciledCount}`, 20, y);
  y += 8;
  doc.setFont(undefined, 'bold');
  doc.text(`Discrepancies: ${report.discrepancyCount}`, 20, y);
  doc.setFont(undefined, 'normal');
  y += 8;
  doc.text(`Pending: ${report.pendingCount}`, 20, y);
  y += 8;
  doc.text(`Total Variance: $${report.totalVariance.toFixed(2)}`, 20, y);

  // Table header
  y += 15;
  doc.setFontSize(8);
  doc.setFont(undefined, 'bold');
  doc.text('Date', 20, y);
  doc.text('Platform', 50, y);
  doc.text('Gross', 85, y);
  doc.text('Fees', 110, y);
  doc.text('Net Payout', 135, y);
  doc.text('Bank', 160, y);
  doc.text('Variance', 180, y);
  doc.text('Status', 195, y);
  y += 8;
  doc.setFont(undefined, 'normal');

  // Items
  report.items.forEach((item: any) => {
    doc.text(new Date(item.date).toLocaleDateString(), 20, y);
    doc.text(item.platform, 50, y);
    doc.text(`$${item.grossAmount.toFixed(2)}`, 85, y);
    doc.text(`$${item.fees.toFixed(2)}`, 110, y);
    doc.text(`$${item.netPayout.toFixed(2)}`, 135, y);
    doc.text(item.actualBankDeposit ? `$${item.actualBankDeposit.toFixed(2)}` : 'N/A', 160, y);
    doc.text(`$${item.variance.toFixed(2)}`, 180, y);
    doc.setFont(undefined, 'bold');
    doc.text(item.status.toUpperCase(), 195, y);
    doc.setFont(undefined, 'normal');
    y += 8;
  });

  // Footer
  doc.setFontSize(8);
  doc.setFont(undefined, 'normal');
  doc.text(`Generated by TaxFlow US on ${new Date().toLocaleDateString()}`, 20, 280);

  doc.save(`1099NEC_Reconciliation_${new Date().toISOString().split('T')[0]}.pdf`);
}
